### ISSUE TITLE
Is "voice" feature actually working correctly?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#47] opened 2023-02-01 15:16 UTC
I suspect that there's something wrong with the code that's deciding whether a "voice" is found for a locale. For example, running Number Compare with `locale=es_MX&locales=*`, I see:

<img width="276" alt="screenshot_2236" src="https://user-images.githubusercontent.com/3046552/216082293-249508fb-a358-4e3c-b613-afdb94f307dc.png">

I find it plausible (but unfortunate) that there is no voice for "español (Mexico)". I find it very difficult to believe that "English (United Kingdom)" is not supported.

Sorry, but given the fact that this is a major feature related to a grant, this feels like it blocks publication until verified.

**Comment by chrisklus** [comment] 2023-02-01 22:33
Thanks for opening this, I was just doing some investigation based on your screenshot from https://github.com/phetsims/number-compare/issues/18#issuecomment-1412620796 and then found you already opened an issue.

The problem seems to be that PhET has locale codes in the style of `xx_XX` and  `SpeechSynthesisVoice` (not a PhET type) has a `lang` property in the style of `xx-XX`.

See the list of available voices (on my machine) below:

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/5618316/216178959-663d68cf-0a62-478d-89cc-ab2e9fb181ce.png">

**Comment by chrisklus** [comment] 2023-02-01 22:36
I propose we convert our locale to `xx-XX` when selecting a voice in NumberSuiteCommonSpeechSynthesisAnnouncer, and if none are available, then search for a truncated version (`xx`) as a fallback, before making the voice unavailable to the user. @pixelzoom thoughts?

**Comment by pixelzoom** [comment] 2023-02-01 23:29
First, I'm not at all familar with how speech synthesis is done. So I'm not sure if we should be addressing this in in sim-specific code, or if there it's something that should be handled by `utteranceQueue.SpeechSynthesisAnnouncer`.

I do feel that having sim-specific code changing the format of locale codes does not sound like a good idea.   If handled in common code, I think the conversion from "xx_XX" to "xx-XX" would be OK.  I'm not sure if it's OK to fallback to "xx" when "xx-XX" is not supported. 

So I think it would be best to consult with someone who has been more involved with locales and speech synthesis -- perhaps @jessegreenberg.

**Comment by pixelzoom** [comment] 2023-02-01 23:30
First, I'm not at all familar with how speech synthesis is done. So I'm not sure if we should be addressing this in in sim-specific code, or if it's something that should be handled in common code -- perhaps in `utteranceQueue.SpeechSynthesisAnnouncer`.

I do feel that having sim-specific code changing the format of locale codes does not sound like a good idea.   If handled in common code, I think the conversion from "xx_XX" to "xx-XX" would be OK.  I'm not sure if it's OK to fallback to "xx" when "xx-XX" is not supported.  Do we do that fallback for strings? If not, then I don't thing it's appropriate to do so for speech.

So I think it would be best to consult with someone who has been more involved with locales and speech synthesis -- perhaps @jessegreenberg.

**Comment by chrisklus** [comment] 2023-02-02 00:01
Right, SpeechSynthesisAnnouncer line ~524 seems like a good spot. Some things used in NumberSuiteCommonSpeechSynthesisAnnouncer should get updated and moved to there.

>I'm not sure if it's OK to fallback to "xx" when "xx-XX" is not supported. Do we do that fallback for strings? If not, then I don't thing it's appropriate to do so for speech.

Good point. I'll talk with @jessegreenberg.

**Comment by chrisklus** [comment] 2023-02-02 00:05
Also noting I found this comment in `utteranceQueue.SpeechSynthesisAnnouncer.getEnglishPrioritizedVoices`:

```js
// most browsers use dashes to separate the local, Android uses underscore
return voice.lang === 'en-US' || voice.lang === 'en_US';
```

so it looks like we'll need to support both.

**Comment by jessegreenberg** [comment] 2023-02-02 15:03
Do we care about the second two characters in the code and do we need to distinguish between locales like `en-US` and `en-UK`? Maybe all of these (including `getEnglishPrioritizedVoices`) should be using `startsWith` instead. For example, the above example would use `voice.lang.startsWith( 'en' )`.

**Comment by pixelzoom** [comment] 2023-02-02 17:04
> Do we care about the second two characters in the code ...

Absolutely yes.

The general locale format is `ll[_CC]`, where `ll` is a language code, and `CC` is a country code.   There are often significant differences (usually pronunciation) between countries that speak the same language.  `en_US` versus `en_UK` is a good example.   At best those differences can be distracting; at worst they can prevent effective communication.

It's no more appropriate to provide "en" voicing to all English-language speakers than it is to provide "en" strings to all English-language speakers.

**Comment by jessegreenberg** [comment] 2023-02-02 17:37
Got it, thanks. I thought PhET only used the language code but see the country code is also used for some:
![image](https://user-images.githubusercontent.com/6396244/216399927-e1e1efdb-8b78-499e-8423-2f8f09ed55aa.png)

**Comment by chrisklus** [comment] 2023-02-06 16:39
I gave this a go in the above commits. Assigning to @jessegreenberg and me to review and/or pair.

**Comment by chrisklus** [comment] 2023-02-06 16:52
Assigning to @pixelzoom to take a look as well for a quick review of behavior.

**Comment by pixelzoom** [comment] 2023-02-06 18:53
Behavior in Number Play looks good.  It's now finding voices for locales that include country codes, like `es_MX` (español (Mexico)) and `en_GB` (English (United Kingdom)).  

I'm not familiar with SpeechSynthesisAnnouncer, so it would be good to have @jessegreenberg review.

**Comment by chrisklus** [comment] 2023-02-06 19:06
This caused some problems that @amanda-phet and I are finding, looking into them shortly.

**Comment by pixelzoom** [comment] 2023-02-06 19:44
I said:
> Behavior in Number Play looks good. It's now finding voices for locales that include country codes, like es_MX (español (Mexico)) and en_GB (English (United Kingdom)).

... but I didn't test with locales that don't have a country code.  And now  those locales (including "English") are not finding a voice:

<img width="430" alt="screenshot_2285" src="https://user-images.githubusercontent.com/3046552/217069452-40c8710f-3d4b-45b4-ba47-e48f86de359d.png">

I backed out https://github.com/phetsims/number-suite-common/commit/5466263a5a42bc9cbf9a9270291c2c343a51a152 and https://github.com/phetsims/utterance-queue/commit/bf7d01fb79944edd52e1d17e177da6fab057abfb in my working copy, and confirmed that they are responsible for this buggy behavior.

**Comment by pixelzoom** [comment] 2023-02-06 19:47
I backed out https://github.com/phetsims/number-suite-common/commit/5466263a5a42bc9cbf9a9270291c2c343a51a152 and https://github.com/phetsims/utterance-queue/commit/bf7d01fb79944edd52e1d17e177da6fab057abfb in my working copy, and confirmed that they are responsible for the new buggy behavior.

**Comment by chrisklus** [comment] 2023-02-06 23:20
@pixelzoom that is the same behavior @amanda-phet and I were observing. I didn't notice initially because English was still working in Chrome (but not Safari).

The problem is that I made the comparison when searching for a voice stricter than it originally was before these changes. All voice locale codes have an associated country code as part of the locale. Our written locale codes only have an associated country when more specificity is needed. For now, I changed the comparison to be more relaxed like it was before, but this doesn't seem good enough long term.

@jessegreenberg and I are going to continue investigating tomorrow. @pixelzoom this should unblock https://github.com/phetsims/number-suite-common/issues/46 (I confirmed that country-less locales are working again).

**Comment by pixelzoom** [comment] 2023-02-07 17:54
Also noted that the voice for "espanol (Mexico)" reads things super fast, like it's meant for screen reader.  Chrome 109 on macOS 13.2.

**Comment by chrisklus** [comment] 2023-02-07 22:20
@jessegreenberg and I met this afternoon and agreed that a nice long term solution might probably involve PhET building a table that prioritizes the top voice(s) we like for each locale + country. This work will also likely involve a table similar to one that @pixelzoom found (https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#US) that maps language codes to a default country (the table linked previously maps language to domain), since a country is needed for every voice if we want to have more control over what options we are choosing from.

We don't see this being high priority for the project since the Number Suite sims are currently the only projects that are using speech synthesis in a language other than English. We also want to acknowledge that there are always going to be limitations to this approach because we don't have control over what voices are loaded on our users machines, and so they may have none of what we prioritized and/or have voices that we've never encountered before.

@jessegreenberg suggested just simply putting the control of selecting a country-specific voice into the hands of the user, and we both really like this idea. We could start by selecting the voice we think is best with the somewhat limited approach we have right now, and then give them the option to re-select any voice that matches just the two letter language code. This has a couple benefits: 

1. When there are multiple voices for a language code or language+country (like what is likely happening in @pixelzoom's case for `es_MX`), then the user can select their favorite sounding voice. This removes the uncertainly we currently have from the browser, as we are just selecting the first voice in the available list.
2. When there is no available voice for a language+country code, the user still has the option to select a voice in that language but for a different country instead of being totally out of luck.
3. As mentioned above, this takes the burden off of PhET of choosing the best voice, which maybe is an impossible task to get full coverage for anyway.

As far as the UI for this control, we are picturing another carousel next to the second language carousel that populates with all voices that match the two letter locale code each time you select a language. The part we did not consider is how to add this same control for the primary locale, since there isn't really room on the Localization tab.

I'm interested in prototyping this first control because it seems really cool to try out regardless if we pursue it. But other than that, next steps are to figure out with @amanda-phet and @kathy-phet if this is a feature we're interested in building out for this publication, and if so, how to design a control that sets the primary language's voice too.

**Comment by chrisklus** [comment] 2023-02-10 00:43
Yesterday, I created a prototype version of this feature that allows for any relevant voice to be selected for a locale:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5618316/217887829-9d156ec1-26bd-41d4-a64a-003549f3a137.png">

I really like the control that it gives to the user and felt that this was a good direction to go. I met with @amanda-phet and she agreed. @amanda-phet also suggested that this control be a consistent UI between the second language control and the localization tab. We are thinking a ComboBox would be best, much like the voice selection ComboBox used in the Voicing preference controls. We think there may need to be some additional label or something that indicates this control is for choosing a voice. @kathy-phet agreed with this sentiment.

Another thing we talked about was a change in philosophy about the locale switch in Number Play. So far, the toggle switch has been a screen-specific control that does not persist state between screens. Since the speech synthesis voice is global setting, there is currently a workaround to keep the state of it independent when the user switches screens. This behavior would get more complicated when adding in voice selection, so we talked about thinking of the toggle as a "shortcut" to the preferences dialog, as that's basically all it's there for now that we have dynamic locale. This means that its state would persist between the Ten and Twenty screens. Upon looking into this more today, I'm not sure it's as essential of a change as I thought, but it certainly simplifies things, so I'll report back how much worse it would be to keep it screen-specific.

I met with @kathy-phet later in the day yesterday and she was on board with the direction and supportive of the additional time needed to build this out. She also mentioned this was supportive of our efforts to give more customization/localization control to our users.

Digging into this more is also revealing some big problems with how much responsibility the SpeechSynthesisButton has, and the fact that there are two instances of it in Number Play. Responsibility for updating the voice should instead be in NumberSuiteCommonPreferences (if the toggle switch model Property is moved there) or NumberSuiteCommonSpeechSynthesisAnnouncer, and responsibility for speaking because of the readAloud=true preference should likely happen in NumberSuiteCommonSpeechSynthesisAnnouncer. Right now there is a problem that the sim reads aloud when readAloud=true and the voice changes, which is a nice feature, but that action can happen on screens that DON'T have speech synthesis features. And because the Twenty screen speaker button is instantiated after the Ten screen, performing this action while on the Ten screen (changing the language and hearing the number read), the Twenty screen number is read out instead of the Ten screen's. This is another symptom of (me doing a bad job of) mixing a global preference with screen-specific state. So, all of that needs to be moved to a global place instead of SpeechSynthesisButton. There, we can filter by screenProperty's value to determine what "state" to read aloud.

This was a big headache to investigate, but I think I have a good understanding of how to make it a lot better. And I've known for a while that SpeechSynthesisButton felt a little sketchy. I believe I told @jessegreenberg way back in causal discussion when I first developed these features that it felt like there should be a more global place that should be responsible for them, so I'm glad we have NumberSuiteCommonSpeechSynthesisAnnouncer to work with now.

I opened https://github.com/phetsims/number-suite-common/issues/51 for these SpeechSynthesisButton/readAloud problems.

**Comment by pixelzoom** [comment] 2023-02-10 02:30
I realize that the screenshot above is a quick prototype.  But some feedback:

User Interface:
* Both lists should be labeled. I don't think you can assume that the user will know that the left list is Lauguages, and the right list is Voices.  I'm not even confident that a user will know what "Voices" is if it's labeled.
* Both lists should be carousels, because we have no idea how many voices may be available for a Language.
* This control takes up a lot of space. I'd like to see a more realistic mockup of the Simulations tab, that shows the other preferences controls that are available.  Is there really space available?
* Is there room for a "Voices" carousel on the Localization tab? There's already a serious space/design problem on that tab, and it involves many stakeholders.

Concerns:
* I agree that there are many problems with the Second Language and Voicing aspects of this sim.  But the current goal is to publish these sims, and explicitly avoid redesign.  It does not sound like that's what is happening here.  And you're treading into territory where there are many stakeholders.  So sanity check: does PhET really want to extend the time to publication?
* The UI you've designed will require either a Carousel that can change its items (not currently supported), or creating a new Carousel instance each time the Lanugage is changed.  Carousel recently saw major revisions, and I doubt that PhET wants to invest more time in it now, so I strongly recommend the latter (new instances of Carousel).
* How long do you think this is going to take?  My optimistic estimate is 2-4 weeks. Longer is you have to modify Carousel or the Localization tab.

**Comment by kathy-phet** [comment] 2023-02-10 13:54
Second language and voicing are must-haves for this sim / line of work, and are critical to attracting more funding as well. So this issue does need to be addressed, and I understand it will take some time. @marlitas - Can you plan to assist on the preferences menu aspects this iteration with your "cross-team" work? Or make a card for your team that explicitly includes Preference menu work to support this. The design doesn't need to be universal (e.g. work for all future sims since we only have this one family of sims that are currently using this kind of feature). As we have more sims with this feature, we will can revise if things don't end up working.

**Comment by marlitas** [comment] 2023-02-10 16:11
Happy to assist with this. I was already planning on doing some cross team collaboration, and will update my team accordingly. Creating a card may help with tracking that, so i will propose that at our standup today.

**Comment by pixelzoom** [comment] 2023-02-13 20:11
Here's what I suggested in 2/13/2023 design meeting, where the combo boxes would be CarouselComboBoxes:

<img width="1071" alt="screenshot_2302" src="https://user-images.githubusercontent.com/3046552/218564509-5669020f-f9db-418c-91d6-df7b4fde96dc.png">

**Comment by pixelzoom** [comment] 2023-02-14 00:13
Notes from 2/13/2023 design meeting:

* Use Carousels labeled Language and Voice for both first and second language. Create a UI component that can be used for both first and second language + voice.
* Add an option to hide default LocalePanel in Localization tab
* "Second Language" control will remain in Simulation tab, though several of us questioned this decision.
* Use the same UI components in both Simulation and Localization tabs.

**Comment by pixelzoom** [comment] 2023-02-14 00:17
Summary of above commits:

* Added `LocalizationPreferencesOptions.includeLocalePanel` (default `true`) that allows sims to opt-out of the default LocalePanel that's typically shown in the Localization tab.

* Used `includeLocalePanel` in number-play-main.ts and number-compare-main.ts, and added a `Text` "Under Construction" placeholder in the Localization tab.  Here's the relevant code in number-play-main.ts:

```typescript
    localizationOptions: {
      includeLocalePanel: false, // We will be substituting our own control for selecting locale.
      customPreferences: [ {
        createContent: () => new Text( 'Under Construction', { font: new PhetFont( 16 ) } )
      } ]
    }
```

The placeholder looks like this:

<img width="1047" alt="screenshot_2303" src="https://user-images.githubusercontent.com/3046552/218605268-4c6ef10c-3621-46bc-b765-7326817f0bef.png">

@chrisklus This is ready for you to replace the `Text` placeholder with a UI component that includes the language + voice Carousels.

**Comment by marlitas** [comment] 2023-02-14 00:18
Got a meeting recap from DL, and will start looking at updating the Localization tab  as well as the Simulation tab to include CarouselComboBoxes for both Language and Voice. 

It seems there was also discussion about having the preferences dialog open to the Simulation tab instead of the Overview tab. That seems like a great idea to me, so I can look at switching that functionality as well.

**Comment by pixelzoom** [comment] 2023-02-14 00:21
> Got a meeting recap from DL, and will start looking at updating the Localization tab as well as the Simulation tab to include CarouselComboBoxes for both Language and Voice.

@marlitas I don't think there's anything that needs to be done for the Localization tab.  @chrisklus and I met about this earlier, and I implemented what we decided --- which is an option to hide the default control for selecting Locale.  See summary in https://github.com/phetsims/number-suite-common/issues/47#issuecomment-1428902492.

@chrisklus will be creating a UI control (2 Carousels) for selecting Language + Voice, and that will be used in both the Simulation tab (for second locale + voice) and in the Localization tab (for primary locale + voice).

**Comment by pixelzoom** [comment] 2023-02-14 00:24
> It seems there was also discussion about having the preferences dialog open to the Simulation tab instead of the Overview tab. That seems like a great idea to me, so I can look at switching that functionality as well.

We decided not to address this specifically for this sim.  If you'd like to move that forward separately, that's fine. But which tab is initially selected is not a blocking concern for publishing Number Play/Compare.

**Comment by chrisklus** [comment] 2023-02-20 23:39
New language and voice controls added in the above commits.

Today in design meeting with @pixelzoom and @amanda-phet, we decided to add the same message from the no-voice pop-up in place of the voice carousel when no voices are available for a language. We also decided to wrap both of those sentences, and @pixelzoom found a way to do this with an option in RichText.  I'll start on this now.

**Comment by chrisklus** [comment] 2023-02-27 23:34
This issue is ready for review. Since there is overlap with https://github.com/phetsims/number-suite-common/issues/52, I recommend reviewing them together. TODOs linked to this issue have been resolved or linked to side issues.

A lot of changes came from this issue, but the main changes were in:

* LanguageAndVoiceControl.ts (including NoVoiceDescriptionNode)
* CarouselItemNode.ts
* SecondLanguageControl.ts
* PreferencesUtteranceQueue

There were also changes in:

* NumberSuiteCommonSpeechSynthesisAnnouncer
* NumberSuiteCommonPreferences

One other thing to note - you may notice for some locales that the word "Language" in the following screenshot has an incorrect translation.
  
<img width="528" alt="image" src="https://user-images.githubusercontent.com/5618316/221671185-07d780bb-7688-4dc5-9ccb-badda9262bdd.png">

This is due to reusing a key that was published with the prototype of Number Play, and will be handled accordingly as described in https://github.com/phetsims/number-suite-common/issues/27#issuecomment-1437668777.

**Comment by pixelzoom** [comment] 2023-03-01 15:05
This is looking really great. Since @amanda-phet gave feedback in https://github.com/phetsims/number-suite-common/issues/52, I'll give my feedback there too. 

Feel free to close this issue.

**Comment by chrisklus** [comment] 2023-03-03 20:46
Thanks @pixelzoom! Closing.

**Closed as completed by chrisklus** 2023-03-03 20:46 UTC
Labels: priority:2-high, status:blocks-sim-publication, status:ready-for-review
