### ISSUE TITLE
Problems with Ten Frame "Return" button in Lab screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#16] opened 2023-01-05 17:39 UTC
The Lab screen has an Undo button for each Ten Frame. Pressing it returns one object in the Ten Frame to its toolbox.

<img width="434" alt="screenshot_2116" src="https://user-images.githubusercontent.com/3046552/210843821-48392bc7-09ef-4a20-af3c-70facec4d731.png">

Problems:

(1) BUG: The Undo button does not appear when you add an object to the Ten Frame. It doesn't appear until you move the Ten Frame after adding an object.

(2) BUG: The Undo button does not seem to work on iPadOS.  It's visible but unresponsive. (iPadOS 16.2 on iPad 6.)

(3) DESIGN:  Why do we need/want an Undo button in such a free-form screen?  Why don't we just add a drag handle to the bottom of the Ten Frame (for moving the Ten Frame if all cells are filled) and allow students to directly drag objects in/out of the Ten Frame?  I find it frustrating that I can drag an object into a Ten Frame, but I can't drag an object out of a Ten Frame -- I need to use an entirely different interaction. Related to #11, there are too many ways to add/remove objects in this screen.  One way that works the same for all objects would be a much better UX.

**Comment by amanda-phet** [comment] 2023-01-05 21:51
Discussed 1/5/23 

* A potential alternative is to be able to grab objects out of the ten frame, but then we would need to add a "handle" at the bottom of the ten frame to move it around 
* Fixing (1) above might make it easier to find the undo button to learn how to edit the ten frame 
* Another option could be to remove any object from the ten frame, and all of the objects rearrange to fill the ten frame appropriately 

(2) is another bug to fix.

**Comment by chrisklus** [comment] 2023-01-06 21:13
Commits pushed above for (1) and (2). Notes:

1. This was a quick fix. I looked to Fractions Intro Lab Screen for a precedent on whether to make the ten frame "selected" when a counting object is released or when it arrives to its spot in the ten frame. Fractions does it on release, so I went ahead with that and it seems nice. I tested with `&speed=0.1` to make sure the ten frame knew how to manage the counting object if the return button is pressed before the counting object reaches its spot, and all seems good.
2. When having no luck on my own, I got help from @marlitas and @zepumph on this one. @zepumph suggested looking to pH Scale's EyeDropperNode for an example, since the whole dropper is draggable but also has a button on it like the return button on the ten frames. We eventually figured out that, like EyeDropperNode, we needed to make the return button `attach: false`. Since the drag listener takes input priority over the whole Node, detaching the button allowed it to be used simultaneously as dragging. We think the resulting behavior is nice. We weren't sure, however, why the behavior for mouse and touch were different, though.

@pixelzoom could you please review to see if both of these issue have the behavior you expect now? And with (2), I've only tested with Chrome's touch device tester, not an actual iPad, so that would be nice to verify. Thanks!

**Comment by amanda-phet** [comment] 2023-01-06 21:37
I decided to check this on my iPad (iOS 16 + Safari), and there is still a bug with this button. 

When I tap it, the button doesn't fire. However, if I tap + drag, it fires on release. 

This does not seem to be a problem on Mac OS + Safari. 

@pixelzoom I'm curious if this is what was actually happening when you opened this issue, or if it's new. Regardless, it is strange since pH Scale doesn't have this issue (on my iPad, running from phettest), so maybe you'll have an idea about what is going on here?

**Comment by zepumph** [comment] 2023-01-06 22:20
@chrisklus @marlitas and I were able to reproduce this on my iPad with chrome and safari. We are working on it!

**Comment by zepumph** [comment] 2023-01-06 23:45
Great progress here! @chrisklus and @marlitas and I were able to reproduce and solve with the commit to come. @chrisklus will increase the touch area just a bit more and call this issue good.

**Comment by chrisklus** [comment] 2023-01-09 15:59
I expanded the touchArea in the above commit. @pixelzoom could you please confirm (1) and (2) from https://github.com/phetsims/number-suite-common/issues/16#issue-1521122904 are fixed? Feel free to close if so.

**Comment by pixelzoom** [comment] 2023-01-09 18:21
I verified that this is behaving as expected on macOS and iPadOS.  Closing.

**Comment by zepumph** [comment] 2023-01-11 21:23
@jonathanolson and I discussed in https://github.com/phetsims/scenery/issues/1515, and he explained that the best pattern would be to add the dragListener only to the node that wants dragging. Note we also agreed that https://github.com/phetsims/scenery/issues/1515 should be solved, and will be fixed separately. 

@chrisklus will you please review this and feel free to reclose.

**Comment by marlitas** [comment] 2023-01-11 22:04
@zepumph Were you able to test this on your iPad to confirm that the "Amanda bug" is still resolved with this change? I don't think @chrisklus or I have an iPad to double check on.

**Comment by zepumph** [comment] 2023-01-11 22:22
I just checked on it works great on an iPad.

**Comment by chrisklus** [comment] 2023-01-18 04:04
Thanks @zepumph @jonathanolson @marlitas! I swear I tried that like 10 minutes into investigating this original issue but the drag behavior got all messed up... who knows. Working great for me now. Closing.

**Closed as completed by chrisklus** 2023-01-18 04:04 UTC
Labels: type:bug, design:general, status:ready-for-review
