### ISSUE TITLE
Require a GitHub issue for TODOs

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#30] opened 2023-01-15 16:45 UTC
In Slack#pistachio on 1/12/23, @zepumph said:
> Since there are so many people working for number-play and associated repos, I would like to add the lint rule where we require issues for todos. There are only 5 failures currently. Do we like that idea to help keep things organized?

There were definitely more than 5 TODOs for "for number-play and associated repos" that do not have an associated GitHub issue.   And I don't see details in that Slack thread about what @zepumph actually did.

What I do see is that `grunt lint` is not identifying all TODOs that are missing associated GitHub issues, for example lots that were identified in https://github.com/phetsims/number-suite-common/issues/28.   And I don't see any specific lint rules being added in package.json files for the number suite.

So a request for @zepumph... Could you please:
(1) Describe what you did 
(2) Fix things so that we cannot inadvenrtently added more TODOs without a GitHub issue

**Comment by zepumph** [comment] 2023-01-16 16:31
1. This particular custom lint rule doesn't behave like standard rules, so my change was https://github.com/phetsims/chipper/commit/58403226fe26e78f23d085b27ce17653a7e7f7fd.
2. I don't know what was happening, and I can't reproduce this error, though I definitely could back when I originally committed the above commit, since I didn't get all TODOs. I'm not really sure how to solve the lint rule since you already fixed things. When I remove one issue link, lets say for something like [this commit line](https://github.com/phetsims/number-suite-common/commit/3d457767b243738d08a8b5e2bf53500304a416c3#diff-e6221839ae6be468be9bb94585fd82b81eccd008470b01758e04cac81f9a8288L164), it immediately marks it as failing.

My best guess for this failure is lint caching; this is because opting in to a new repo for this rule involves changing the rule itself, which is heavily cached, and could result in different behavior on different machines depending on how that cache is broken. 

I first want to update to rule to get away from that paradigm. I know why it was originally done like that, because we only put that rule into anything in phetLibs that isn't scenery,kit,dot, and perennial-alias. Now though, I feel like it would be better to make it opt out, depending on how much effort it would be to make that happen. I'll take a look. We can always make it opt in.

**Comment by zepumph** [comment] 2023-01-16 18:14
Over in https://github.com/phetsims/chipper/issues/1372#issuecomment-1384409024, I updated the lint rule so that it behaves as expected better. 

I also realized that in https://github.com/phetsims/chipper/commit/58403226fe26e78f23d085b27ce17653a7e7f7fd, I didn't add `counting-common`. We should do that!

**Comment by pixelzoom** [comment] 2023-01-17 23:11
Looks good. Back to @zepumph in case there's anything else to do. Feel free to close.

**Comment by chrisklus** [comment] 2023-01-19 16:13
>I also realized that in https://github.com/phetsims/chipper/commit/58403226fe26e78f23d085b27ce17653a7e7f7fd, I didn't add `counting-common`. We should do that! 

I added counting-common to todo-should-have-issue over in https://github.com/phetsims/counting-common/issues/11. All four repos now have this lint rule and are passing.

Passing back to @zepumph for final review in case there's any work left from https://github.com/phetsims/number-suite-common/issues/30#issuecomment-1384296235.

**Comment by zepumph** [comment] 2023-01-19 16:34
Amazing and I love https://github.com/phetsims/counting-common/commit/9f170ec0e6249f64e45e6bdefe40d816485f74af. Closing

**Closed as completed by zepumph** 2023-01-19 16:34 UTC
Labels: status:ready-for-review
