### ISSUE TITLE
Nothing is heard when switching voices in the localization tab

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-suite-common#55] opened 2023-03-10 20:35 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
13.2.1

**Browser**
Safari 

**Problem description**
While testing https://github.com/phetsims/qa/issues/917, when changing the locale and voice in the Localization Tab of the Preferences Menu I didn't hear anything. Based on https://github.com/phetsims/number-suite-common/issues/52#issuecomment-1437575156 and a slack conversation with @chrisklus, it was discovered that this feature was working in the unbuilt version but not working in 1.0.0-dev.4. 

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Compare‬
URL: https://phet-dev.colorado.edu/html/number-compare/1.0.0-dev.4/phet/number-compare_all_phet.html
Version: 1.0.0-dev.4 2023-03-09 16:37:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
Language: en-US
Window: 1203x654
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by chrisklus** [comment] 2023-03-15 01:10
Thanks @Nancy-Salpepi! I think this was actually caused by https://github.com/phetsims/number-compare/issues/20, instead of https://github.com/phetsims/utterance-queue/issues/108 like I was previously thinking. Leaving self assigned to verify in the new dev version.

**Comment by chrisklus** [comment] 2023-03-15 01:35
This appears to be fixed in dev.6, closing.

**Closed as completed by chrisklus** 2023-03-15 01:35 UTC
Labels: type:bug

**Comment by chrisklus** [comment] 2023-03-15 14:36
Also, thanks to @zepumph for some great help on this issue. We refactored Number Play and Number Compare to use one announcer and utterance queue. I'm liking these changes!
