### ISSUE TITLE
readAloud using English voice when translated voice is not found

### ISSUE THREAD

**Issue by marlitas** [phetsims/number-suite-common#46] opened 2023-02-01 00:09 UTC
When a device does not have the voice associated to the chosen locale, the English voice still reads out the string. Ideally read aloud would be silent if there is no voice found for that locale. The speech synthesis button is greyed out appropriately.

**Comment by pixelzoom** [comment] 2023-02-01 00:15
Here's an untested patch.  

<details>
<summary>patch</summary>

```diff
Subject: [PATCH] hide irrelevant Preferences controls, https://github.com/phetsims/number-suite-common/issues/43
---
Index: js/common/view/SpeechSynthesisButton.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/SpeechSynthesisButton.ts b/js/common/view/SpeechSynthesisButton.ts
--- a/js/common/view/SpeechSynthesisButton.ts	(revision f05dbce511e17ef993327dc8618974022b78e4b6)
+++ b/js/common/view/SpeechSynthesisButton.ts	(date 1675210410951)
@@ -73,8 +73,18 @@
     };
 
     // read numeric numbers aloud if the current number changes (or the second number, on the 'Compare' screen)
-    Multilink.lazyMultilink( [ options.numberProperty, options.secondNumberProperty ], () => {
-      if ( preferences.readAloudProperty.value ) {
+    Multilink.lazyMultilink( [
+      options.numberProperty,
+      options.secondNumberProperty,
+      preferences.readAloudProperty,
+      preferences.showSecondLocaleProperty,
+      speechSynthesisAnnouncer.primaryLocaleVoiceEnabledProperty,
+      speechSynthesisAnnouncer.secondaryLocaleVoiceEnabledProperty
+    ], ( number, secondNumber, readAloud, showSecondLocale, primaryLocaleVoiceEnabled, secondaryLocaleVoiceEnabled ) => {
+      const doReadAloud = showSecondLocale ?
+                          readAloud && ( !primaryLocaleVoiceEnabled || !secondaryLocaleVoiceEnabled ) :
+                          readAloud && !primaryLocaleVoiceEnabled;
+      if ( doReadAloud ) {
         listener();
       }
     } );
```

</details>

Note that the new dependencies above were copied from the Multilink in ReadAloudControl.ts:

```typescript
    Multilink.multilink( [ preferences.readAloudProperty, preferences.showSecondLocaleProperty,
        speechSynthesisAnnouncer.primaryLocaleVoiceEnabledProperty,
        speechSynthesisAnnouncer.secondaryLocaleVoiceEnabledProperty ],
      ( readAloud, showSecondLocale, primaryLocaleVoiceEnabled, secondaryLocaleVoiceEnabled ) => {
        missingVoiceWarning.visible = showSecondLocale ?
                                      readAloud && ( !primaryLocaleVoiceEnabled || !secondaryLocaleVoiceEnabled ) :
                                      readAloud && !primaryLocaleVoiceEnabled;
      } );
```

**Comment by pixelzoom** [comment] 2023-02-01 00:18
I'll take this one, since I have a patch above that I didn't have time to test.

**Comment by pixelzoom** [comment] 2023-02-06 19:54
@chrisklus FYI I'm blocked on this until https://github.com/phetsims/number-suite-common/issues/47#issuecomment-1419649995 is resolved.  I had to back out the patch below because I couldn't confirm it's behavior while the mapping from locale to voice is buggy.

<details>
<summary>Patch</summary>

```diff
Subject: [PATCH] left justify LocaleSwitch, https://github.com/phetsims/number-compare/issues/18
---
Index: number-suite-common/js/common/view/NumberSuiteCommonSpeechSynthesisAnnouncer.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/number-suite-common/js/common/view/NumberSuiteCommonSpeechSynthesisAnnouncer.ts b/number-suite-common/js/common/view/NumberSuiteCommonSpeechSynthesisAnnouncer.ts
--- a/number-suite-common/js/common/view/NumberSuiteCommonSpeechSynthesisAnnouncer.ts	(revision 544e92d9775949048b670e834d459332e782b286)
+++ b/number-suite-common/js/common/view/NumberSuiteCommonSpeechSynthesisAnnouncer.ts	(date 1675713087298)
@@ -23,8 +23,10 @@
   private readonly secondLocaleProperty: TReadOnlyProperty<Locale>;
   public readonly primaryLocaleVoiceEnabledProperty: TReadOnlyProperty<boolean>;
   public readonly secondaryLocaleVoiceEnabledProperty: TReadOnlyProperty<boolean>;
+  public readonly voiceIsMissingProperty: TReadOnlyProperty<boolean>;
 
-  public constructor( secondLocaleProperty: TReadOnlyProperty<Locale> ) {
+  public constructor( secondLocaleProperty: TReadOnlyProperty<Locale>,
+                      showSecondLocaleProperty: TReadOnlyProperty<boolean> ) {
     super();
 
     this.updateVoiceListener = () => this.updateVoice();
@@ -36,6 +38,12 @@
     this.secondaryLocaleVoiceEnabledProperty = new DerivedProperty( [ secondLocaleProperty, this.voiceProperty ],
       locale => this.testVoiceForLocale( locale ) );
 
+    this.voiceIsMissingProperty = new DerivedProperty(
+      [ showSecondLocaleProperty, this.primaryLocaleVoiceEnabledProperty, this.secondaryLocaleVoiceEnabledProperty ],
+      ( showSecondLocale, primaryLocaleVoiceEnabled, secondaryLocaleVoiceEnabled ) =>
+        showSecondLocale ? !secondaryLocaleVoiceEnabled : !primaryLocaleVoiceEnabled
+    );
+
     // When the SpeechSynthesisAnnouncer becomes initialized or when voices change, update the voice
     // currently being used by this Announcer.
     this.voicesProperty.lazyLink( this.updateVoiceListener );
Index: number-suite-common/js/common/view/ReadAloudControl.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/number-suite-common/js/common/view/ReadAloudControl.ts b/number-suite-common/js/common/view/ReadAloudControl.ts
--- a/number-suite-common/js/common/view/ReadAloudControl.ts	(revision 544e92d9775949048b670e834d459332e782b286)
+++ b/number-suite-common/js/common/view/ReadAloudControl.ts	(date 1675713087301)
@@ -7,39 +7,38 @@
  *
  * @author Chris Klusendorf (PhET Interactive Simulations)
  * @author Marla Schulz (PhET Interactive Simulations)
+ * @author Chris Malley (PixelZoom, Inc.)
  */
 
-import { Color, Node, Path, Text, VBox } from '../../../../scenery/js/imports.js';
+import { Color, Path, Text, VBox } from '../../../../scenery/js/imports.js';
 import numberSuiteCommon from '../../numberSuiteCommon.js';
-import NumberSuiteCommonPreferences from '../model/NumberSuiteCommonPreferences.js';
 import PreferencesControl from '../../../../joist/js/preferences/PreferencesControl.js';
 import NumberSuiteCommonStrings from '../../NumberSuiteCommonStrings.js';
 import TReadOnlyProperty from '../../../../axon/js/TReadOnlyProperty.js';
 import PreferencesDialogConstants from '../../../../joist/js/preferences/PreferencesDialogConstants.js';
 import ToggleSwitch from '../../../../sun/js/ToggleSwitch.js';
-import NumberSuiteCommonSpeechSynthesisAnnouncer from './NumberSuiteCommonSpeechSynthesisAnnouncer.js';
-import Multilink from '../../../../axon/js/Multilink.js';
 import PhetFont from '../../../../scenery-phet/js/PhetFont.js';
 import exclamationTriangleSolidShape from '../../../../sherpa/js/fontawesome-5/exclamationTriangleSolidShape.js';
 import NumberSuiteCommonConstants from '../NumberSuiteCommonConstants.js';
+import DerivedProperty from '../../../../axon/js/DerivedProperty.js';
+import Property from '../../../../axon/js/Property.js';
 
-export default class ReadAloudControl<T extends NumberSuiteCommonPreferences,
-  A extends NumberSuiteCommonSpeechSynthesisAnnouncer> extends Node {
+const WARNING_TEXT_OPTIONS = {
+  font: new PhetFont( 14 )
+};
 
-  public constructor( preferences: T,
-                      speechSynthesisAnnouncer: A,
+export default class ReadAloudControl extends VBox {
+
+  public constructor( readAloudProperty: Property<boolean>,
+                      voiceIsMissingProperty: TReadOnlyProperty<boolean>,
                       labelStringProperty: TReadOnlyProperty<string>,
                       descriptionStringProperty: TReadOnlyProperty<string>,
                       visible: boolean ) {
 
-    super( {
-      visible: visible
-    } );
-
-    const toggleSwitch = new ToggleSwitch( preferences.readAloudProperty, false, true,
+    // Toggle switch for turning 'Read Aloud' on and off
+    const toggleSwitch = new ToggleSwitch( readAloudProperty, false, true,
       PreferencesDialogConstants.TOGGLE_SWITCH_OPTIONS );
-
-    const control = new PreferencesControl( {
+    const toggleControl = new PreferencesControl( {
       labelNode: new Text( labelStringProperty, {
         fontSize: NumberSuiteCommonConstants.PREFERENCES_FONT_SIZE,
         fontWeight: 'bold'
@@ -50,47 +49,35 @@
       controlNode: toggleSwitch,
       ySpacing: NumberSuiteCommonConstants.PREFERENCES_DESCRIPTION_Y_SPACING
     } );
-    this.addChild( control );
 
-    const missingVoiceWarningTextOptions = {
-      font: new PhetFont( 14 )
-    };
-    const noDeviceFoundDescriptionText = new Text( NumberSuiteCommonStrings.noDeviceFoundDescriptionStringProperty,
-      missingVoiceWarningTextOptions );
-    const yourDeviceMaySupportDescriptionText = new Text( NumberSuiteCommonStrings.yourDeviceMaySupportDescriptionStringProperty,
-      missingVoiceWarningTextOptions );
-
-    const missingVoiceWarning = new Node();
-    const missingVoiceWarningMessage = new VBox( {
-      children: [ noDeviceFoundDescriptionText, yourDeviceMaySupportDescriptionText ],
+    // Warning message, to notify the user that there is no voice for the selected locale.
+    const warningMessage = new VBox( {
+      children: [
+        new Text( NumberSuiteCommonStrings.noDeviceFoundDescriptionStringProperty, WARNING_TEXT_OPTIONS ),
+        new Text( NumberSuiteCommonStrings.yourDeviceMaySupportDescriptionStringProperty, WARNING_TEXT_OPTIONS )
+      ],
       spacing: 8,
       align: 'left'
     } );
-    missingVoiceWarning.addChild( missingVoiceWarningMessage );
-
     const warningIcon = new Path( exclamationTriangleSolidShape, {
       fill: new Color( 240, 79, 79 ),
       maxWidth: 30
     } );
-    missingVoiceWarning.addChild( warningIcon );
-    this.addChild( missingVoiceWarning );
+    const warningNode = new VBox( {
+      children: [ warningMessage, warningIcon ],
+      align: 'center',
+      spacing: 14,
+      visibleProperty: new DerivedProperty( [ readAloudProperty, voiceIsMissingProperty ],
+        ( readAloud, voiceIsMissing ) => readAloud && voiceIsMissing )
+    } );
 
-    missingVoiceWarningMessage.left = control.left;
-    warningIcon.centerX = missingVoiceWarningMessage.centerX;
-    missingVoiceWarning.top = control.bottom + 24;
-    missingVoiceWarningMessage.top = warningIcon.bottom + 14;
-
-    Multilink.multilink( [
-        preferences.readAloudProperty,
-        preferences.showSecondLocaleProperty,
-        speechSynthesisAnnouncer.primaryLocaleVoiceEnabledProperty,
-        speechSynthesisAnnouncer.secondaryLocaleVoiceEnabledProperty
-      ],
-      ( readAloud, showSecondLocale, primaryLocaleVoiceEnabled, secondaryLocaleVoiceEnabled ) => {
-        missingVoiceWarning.visible = showSecondLocale ?
-                                      readAloud && ( !primaryLocaleVoiceEnabled || !secondaryLocaleVoiceEnabled ) :
-                                      readAloud && !primaryLocaleVoiceEnabled;
-      } );
+    super( {
+      children: [ toggleControl, warningNode ],
+      excludeInvisibleChildrenFromBounds: false,
+      visible: visible,
+      spacing: 24,
+      align: 'left'
+    } );
   }
 }
 
Index: number-compare/js/common/view/numberCompareSpeechSynthesisAnnouncer.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/number-compare/js/common/view/numberCompareSpeechSynthesisAnnouncer.ts b/number-compare/js/common/view/numberCompareSpeechSynthesisAnnouncer.ts
--- a/number-compare/js/common/view/numberCompareSpeechSynthesisAnnouncer.ts	(revision e362c5b568ff034150a39cb6703f0b882794863b)
+++ b/number-compare/js/common/view/numberCompareSpeechSynthesisAnnouncer.ts	(date 1675713110705)
@@ -11,8 +11,10 @@
 import numberCompare from '../../numberCompare.js';
 import numberComparePreferences from '../model/numberComparePreferences.js';
 
-const numberCompareSpeechSynthesisAnnouncer =
-  new NumberSuiteCommonSpeechSynthesisAnnouncer( numberComparePreferences.secondLocaleProperty );
+const numberCompareSpeechSynthesisAnnouncer = new NumberSuiteCommonSpeechSynthesisAnnouncer(
+  numberComparePreferences.secondLocaleProperty,
+  numberComparePreferences.showSecondLocaleProperty
+);
 
 numberCompare.register( 'numberCompareSpeechSynthesisAnnouncer', numberCompareSpeechSynthesisAnnouncer );
 export default numberCompareSpeechSynthesisAnnouncer;
\ No newline at end of file
Index: number-play/js/number-play-main.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/number-play/js/number-play-main.ts b/number-play/js/number-play-main.ts
--- a/number-play/js/number-play-main.ts	(revision 77dcf361a29dac504d8ab482770c268168ad631f)
+++ b/number-play/js/number-play-main.ts	(date 1675713100321)
@@ -48,8 +48,11 @@
     },
     audioOptions: {
       customPreferences: [ {
-        createContent: () => new ReadAloudControl( numberPlayPreferences, numberPlaySpeechSynthesisAnnouncer,
-          NumberPlayStrings.hearTotalStringProperty, NumberPlayStrings.hearTotalDescriptionStringProperty,
+        createContent: () => new ReadAloudControl(
+          numberPlayPreferences.readAloudProperty,
+          numberPlaySpeechSynthesisAnnouncer.voiceIsMissingProperty,
+          NumberPlayStrings.hearTotalStringProperty,
+          NumberPlayStrings.hearTotalDescriptionStringProperty,
           NumberSuiteCommonPreferencesNode.hasScreenType( TenScreen ) || NumberSuiteCommonPreferencesNode.hasScreenType( TwentyScreen ) )
       } ]
     }
Index: number-compare/js/number-compare-main.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/number-compare/js/number-compare-main.ts b/number-compare/js/number-compare-main.ts
--- a/number-compare/js/number-compare-main.ts	(revision e362c5b568ff034150a39cb6703f0b882794863b)
+++ b/number-compare/js/number-compare-main.ts	(date 1675713110707)
@@ -44,8 +44,10 @@
     },
     audioOptions: {
       customPreferences: [ {
-        createContent: () => new ReadAloudControl( numberComparePreferences,
-          numberCompareSpeechSynthesisAnnouncer, NumberCompareStrings.hearNumberSentenceStringProperty,
+        createContent: () => new ReadAloudControl(
+          numberComparePreferences.readAloudProperty,
+          numberCompareSpeechSynthesisAnnouncer.voiceIsMissingProperty,
+          NumberCompareStrings.hearNumberSentenceStringProperty,
           NumberCompareStrings.hearNumberSentenceDescriptionStringProperty,
           NumberSuiteCommonPreferencesNode.hasScreenType( CompareScreen ) )
       } ]
Index: number-play/js/common/view/numberPlaySpeechSynthesisAnnouncer.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/number-play/js/common/view/numberPlaySpeechSynthesisAnnouncer.ts b/number-play/js/common/view/numberPlaySpeechSynthesisAnnouncer.ts
--- a/number-play/js/common/view/numberPlaySpeechSynthesisAnnouncer.ts	(revision 77dcf361a29dac504d8ab482770c268168ad631f)
+++ b/number-play/js/common/view/numberPlaySpeechSynthesisAnnouncer.ts	(date 1675713100320)
@@ -11,8 +11,10 @@
 import NumberSuiteCommonSpeechSynthesisAnnouncer from '../../../../number-suite-common/js/common/view/NumberSuiteCommonSpeechSynthesisAnnouncer.js';
 import numberPlayPreferences from '../model/numberPlayPreferences.js';
 
-const numberPlaySpeechSynthesisAnnouncer =
-  new NumberSuiteCommonSpeechSynthesisAnnouncer( numberPlayPreferences.secondLocaleProperty );
+const numberPlaySpeechSynthesisAnnouncer = new NumberSuiteCommonSpeechSynthesisAnnouncer(
+  numberPlayPreferences.secondLocaleProperty,
+  numberPlayPreferences.showSecondLocaleProperty
+);
 
 numberPlay.register( 'numberPlaySpeechSynthesisAnnouncer', numberPlaySpeechSynthesisAnnouncer );
 export default numberPlaySpeechSynthesisAnnouncer;
\ No newline at end of file

```

</details>

**Comment by chrisklus** [comment] 2023-02-06 23:21
As of https://github.com/phetsims/utterance-queue/commit/981537e9a6fc60f9d3ee8c236a73e13db1f25fbd, you should be all set to continue here @pixelzoom.

**Comment by pixelzoom** [comment] 2023-02-07 17:51
There were 2 problems here, addressed in the above commits:

(1) In NumberSuiteCommonSpeechSynthesisAnnouncer `updateVoice`, `this.voiceProperty` was not being set to `null` when no voice was found. So we were left with a stale voice.  The fix is:

```diff
      const translatedVoices = this.getPrioritizedVoicesForLocale( locale );
      if ( translatedVoices.length > 0 ) {
        this.voiceProperty.value = translatedVoices[ 0 ];
      }
+      else {
+        this.voiceProperty.value = null;
+      }
```

(2) SpeechSynthesisButton `const listener` was missing dependencies.  The correct derivation is:

```typescript
    Multilink.lazyMultilink(
      [ options.numberProperty, options.secondNumberProperty, options.comparisonSignsAndTextVisibleProperty, speechSynthesisAnnouncer.voiceProperty ],
      ( number, secondNumber, comparisonSignsAndTextVisible, voice ) => {
        if ( preferences.readAloudProperty.value && comparisonSignsAndTextVisible && voice ) {
          listener();
        }
      } )
```

Here's the expected behavior when the "Hear..." preference is "on". I walked through this with @chrisklus over Zoom:

* If the selected locale has no voice, nothing will be read.
* When switching between primary and secondary locale, if the selected locale has a voice, the total/sentence will be read.
* If secondary locale is selected (by switch or radio buttons), choosing a locale from Second Language preference will read the total/sentence.
* In Number Compare, if the comparisonSignsAndText checkbox is off, nothing will be read. When it is toggled on, the sentence will be read, if the selected locale has a voice.

Over to @chrisklus for review.

**Comment by chrisklus** [comment] 2023-02-27 23:51
Thanks @pixelzoom, these changes look great. Much of this stuff has since been moved around in https://github.com/phetsims/number-suite-common/issues/47, https://github.com/phetsims/number-suite-common/issues/52, and https://github.com/phetsims/number-suite-common/issues/51 but these changes helped guide my thinking and gave a reference to watch out for regressions. Closing.

**Closed as completed by chrisklus** 2023-02-27 23:52 UTC
Labels: type:bug, status:blocks-sim-publication, status:ready-for-review
